name: Check for l10n updates
on:

  push:


jobs:
  update-translations:
    runs-on: windows-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Add remote
      run: |
        git remote add org https://github.com/nvdaaddons/readFeeds
        git fetch org
        git merge org/stable