name: Lint diff

on:
  pull_request:
    branches:
      - master

jobs:

  diff:

    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install -r .github/extraResources/requirements.txt
    #- name: Get diff url
      #id: diffUrl
      #uses: actions/github-script@v3
      #with:
        #github-token: ${{secrets.GITHUB_TOKEN}}
        #script: |
          #const diff_url = context.payload.pull_request.diff_url
          #const result = await github.request(diff_url)
          #return result.data
    - name: Lint
      run: |
        git diff -U0 origin/master...HEAD > flake8.diff
        type flake8.diff | flake8 --diff --output-file=flake8.txt --tee --config=.github/extraResources/flake8.ini
    if: failure():
    - name: Upload lint results
      uses: actions/upload-artifact@v2
      with:
        name: flake8
        path: flake8.txt
