name: Build and test addon with NVDA's plugin

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies and build add-on
      run: |
        pip install scons
        pip install Markdown
        pip install flake8
        pip install flake8-tabs
        scons
    - name: Upload artifact 
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: *.nvda-addon
        