name: Build and release NVDA add-on

on: [push, pull_request]

jobs:

  addon:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install scons
        pip install Markdown
        pip install flake8
        pip install flake8-tabs
    - name: Download flake8.ini
      run: curl -O https://github.com/nvaccess/nvda/blob/master/tests/lint/flake8.ini
    - name: Lint add-on
      run: flake8 --config .github\extraResources\setup.cfg --exit-zero addon
    - name: Build add-on
      run: scons
      shell: cmd
    - name: Upload add-on
      uses: actions/upload-artifact@v2
      with:
        name: nvda-addon
        path: "*.nvda-addon"
    - name: Create Release
      if: contains(github.ref, '/tags/')
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        prerelease: ${{ endsWith(github.ref, '-dev') }}
    - name: Upload binaries to release
      if: contains(github.ref, '/tags/')
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: '*.nvda-addon'
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true        

  nvda:
  
    needs: addon
  
    runs-on: windows-latest

    steps:
    - name: Set up Python 3.7 x86
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x86
    - name: Checkout NVDA
      uses: actions/checkout@v2
      with:
        repository: nvaccess/nvda
        submodules: true
    - name: Prepare NVDA's source tree
      run: scons source
      shell: cmd
    - name: Download add-on
      uses: actions/download-artifact@v2
      with:
        name: nvda-addon
    - name: Copy add-on
      run: |
        move *.nvda-addon addon.zip
        expand-archive addon.zip source\userConfig\addons\addon
    - name: Start NVDA
      run: |
        cd source
        pythonw.exe nvda.pyw -m --debug-logging
        ping 127.0.0.1 /n 20
    - name: Quit NVDA
      run: |
        pythonw.exe nvda.pyw -q
        ping 127.0.0.1 /n 20
    - name: Upload log
      uses: actions/upload-artifact@v2
      with:
        name: nvda-log
        path: source\nvda.log
