name: Send to addonFiles

on:
  release:
    types:
      - created

jobs:

  sendToAddonFiles:
    runs-on: windows-latest
    steps:
    - name: Checkout addonFiles
      uses: actions/checkout@v2
      with:
        repository: nvdaes/addonFiles
    - name: Create branch
      run: git checkout -b ${{ github.repository.name }}-${{ github.release.tag_name }}
        